import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: 'Home',
    href: '/'
  },
   {
    label: 'Article',
    href: '/article'
  },
   {
    label: 'About',
    href: '/about'
  },
  {
    label: 'Login',
    href: '/login'
  },
  {
    label: 'Signup',
    href: '/signup'
  },
  {
    label: 'Dashboard',
    href: '/dashboard'
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow-lg sticky top-0 left-0 w-full py-6">
          <h1>AlgoAlchemy</h1>
          <div>
          {
            menus.map((item,index)=>(
              <Link key={index} href={item.href}>{item.label}</Link>
            ))
          }
          </div>
        </nav>
        <section>{children}</section>
        <footer>my Footer</footer>
      </body>
    </html>
  );
}
