import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menus = [
  {
    label: 'Home',
    href: '/',
    button: false
  },
   {
    label: 'Article',
    href: '/article',
    button: false
  },
   {
    label: 'About',
    href: '/about',
    button: false
  },
  // {
  //   label: 'Login',
  //   href: '/login',
  //   button: false
  // },
  // {
  //   label: 'Signup',
  //   href: '/signup',
  //   button: true
  // },
  {
    label: 'Dashboard',
    href: '/Dashboard',
    button: false
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="px-[7%] bg-white shadow-lg sticky top-0 left-0 w-full py-6 flex justify-between items-center">
          <Link href="/" className="text-left text-2xl font-bold">AlgoAlchemy</Link>
          <div className="flex gap-5 justify-center flex-1 items-center">
          {
            menus.map((item,index)=>(
              <Link key={index} href={item.href} className={item.button ? 'bg-violet-600 px-8 py-3 rounded text-white' : null}>{item.label}</Link>
            ))
          }
          </div>
          <div className="flex items-center gap-4">
            <input type="text" placeholder="Search" className="border px-3 py-1 rounded-md" />
            <Link href="/login">Login</Link>
            <Link
             href="/signup"
             className="bg-violet-600 px-4 py-2 rounded text-white"
             >Signup</Link>

          </div>
        </nav>
        <section className="px-[5%] py-[10%]">{children}</section>
        <footer className="bg-gray-200 h-[450px] flex items-center justify-center text-3xl">my Footer</footer>
      </body>
    </html>
  );
}
